version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: contents
        files: # determine which files contents to validate
          pr_diff: true # If true, validator will grab all the added and modified files in the head of the PR
          ignore: ['.github/mergeable.yml'] # Optional, default ['.github/mergeable.yml'], pattern of files to ignore
        must_exclude:
          regex: 'NOCOMMIT|FIXME'
          message: 'Non-commitable keyword found!'
